### ISSUE TITLE
Highlight current page/item in the sidebar

### ISSUE THREAD

**Issue by mhamwala** [appsody/website#106]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
We could make the headings in the sidebar bold when you are on that selected page, makes it easier to see what page you are on when you are browsing the website.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by neeraj-laad** [comment]
Just renamed the issue to describe the problem vs a specific solution.

**Comment by tomleah** [comment]
We can use `activeClassName` to set the style based on the current active page. See https://spectrum.chat/gatsby-js/general/best-way-to-show-active-links-in-the-navigation~b698900b-cea6-44f8-8f35-d7015365ff18
