### ISSUE TITLE
Document how you can extend a stack

### ISSUE THREAD

**Issue by mhamwala** [appsody/website#123]
**Is your feature request related to a problem? Please describe.**
We currently don't have much documentation on how you can extend a stack

**Describe the solution you'd like**
details of how you can extend a stack:

We inherit from other stacks by providing the stack you want to inherit from in the `Dockerfile-stack`

For example the nodejs-express stack inherits from the nodejs stack image, specified in the Dockerfile-stack like so:
`From appsody/nodejs:0.2`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mhamwala** [comment]
This could sit in the contributing docs but open to suggestions..

**Comment by tomleah** [comment]
I don't think this should be CONTRIBUTING.md, as this is a stack specific doc and not to do with general contributions. My suggestion would be to add this as a section in `stacks/create-or-modify.md`

**Comment by neeraj-laad** [comment]
Should be addressed by creating /modifying stack documentation we are working on? It does not make sense on it's own. 

@mhamwala @tomleah would like your thoughts on this.

**Comment by tomleah** [comment]
I think this should belong in the creating stacks doc. Happy to close this issue and include in https://github.com/appsody/website/issues/79

**Comment by mhamwala** [comment]
I agree! I think it makes sense for this to be in creating stacks for the time being. atm i don't think we have enough content for it to be in a separate doc
