### ISSUE TITLE
--- name: Bug report about: Create a report to help us improve title: '' labels: '' assignees: '' ---

### ISSUE THREAD

**Issue by sdaschner** [appsody/website#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by sdaschner** [comment]
Sorry, my `hub` CLI went crazy :)

**Comment by edwiin17** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Actual behaviour**
> What is the actual behaviour.
> 
> **Environment Details (please complete the following information):**
>  - OS: [e.g. iOS]
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **If applicable please specify:**
>  - CLI version:
>  - Stack you are using:
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by edwiin17** [comment]
````
``
````> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Actual behaviour**
> What is the actual behaviour.
> 
> **Environment Details (please complete the following information):**
>  - OS: [e.g. iOS]
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **If applicable please specify:**
>  - CLI version:
>  - Stack you are using:
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.
