### ISSUE TITLE
Document stack structure & layout

### ISSUE THREAD

**Issue by sdaschner** [appsody/website#139]
A stack is required to define and setup certain things, mainly environment variables, such as `APPSODY_RUN`.

**Describe the bug**
We need to document how the required structure of a stack must look like, as well as the process, what is happening on the various lifecycles. It's also important to know which process is executed in which way (synchronous, asynchronous, which commands happens in parallel, etc.).

**Expected behavior**
A clear and extensive description of the requirements and internals of an appsody stack.

**Actual behaviour**
A how to get started with extending a stack (https://appsody.dev/docs/stacks/create-or-modify#Modifying-a-stack), but nothing about the internals.

This might be connected with #123.

**Comment by sdaschner** [comment]
We also need a place for "advanced" users where internals and env vars are documented, e.g. `APPSODY_PULL_POLICY` as described in appsody/appsody#114 and maybe others.

**Comment by neeraj-laad** [comment]
@sdaschner Thanks for raising This. We will get to this shortly.

**Comment by neeraj-laad** [comment]
WE have recently updated our docs for creating and modifying stacks with a lot more detail. Also we have added a table with full list of appsody environment variables for stacks.

**Comment by sdaschner** [comment]
Very cool, thanks! Will get back in case I stumble on smth.

One thing: can the page for [environment variables](https://appsody.dev/docs/stacks/environment-variables) be added to the navigation?
