### ISSUE TITLE
Modifying stacks in docSidebar is not being highlighted

### ISSUE THREAD

**Issue by skoh7645** [appsody/website#142]
**Describe the bug**
When you click on the "Modifying Stacks" section in the docSidebar, the title is not being highlighted on the sidebar.

**To Reproduce**
1. Go to 'http://localhost:8000/docs'
2. Click on 'Modifying Stacks' section in sidebar
3. Current section is not highlighted

**Expected behavior**
"Modifying Stacks" title is highlighted on sidebar when clicked.

**Actual behaviour**
"Creating Stacks" is highlighted instead because "Modifying Stacks" is part of that page.

**Environment Details (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by tomleah** [comment]
We should have a long term fix for this problem. I think this case will be solved when these 2 docs are completely split when more content is added.

**Comment by skoh7645** [comment]
This issue has been resolved as the doc have been split. Closing this issue.
