### ISSUE TITLE
Instructions for Enterprise Windows users has errors

### ISSUE THREAD

**Issue by makandre** [appsody/website#147]
**Describe the bug**

The instructions at https://appsody.dev/docs/faq are:

```
1. Create a new project (pick a folder that is outside of your home directory, or Docker will not have access to it).

2. Run appsody init --config C:\my-appsody-config-dir.appsody-config.yaml

3. notepad C:\my-appsody-config-dir\.appsody-config.yaml

4. Change the entry home: to C:\my-appsody-config-dir

5. Run appsody run --config C:\my-appsody-config-dir\.appsody.yaml
```

There are a couple problems:

- It does not say `my-appsody-config-dir` needs to be created first
- Shouldn't the path be `C:\my-appsody-config-dir\.appsody.yaml`? (missing path separator and filename difference)

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by makandre** [comment]
It appears the instructions came from https://github.com/appsody/appsody/issues/24 but there are some typos.

**Comment by jgwest** [comment]
I hit the same issues as Andrew above, and if it helps these specific steps worked for me (where `c:\mya` is the app dir):
```
mkdir c:\mya
cd \mya
appsody init java-microprofile

mkdir C:\my-appsody-config-dir\
appsody init --config C:\my-appsody-config-dir\.appsody-config.yaml
notepad C:\my-appsody-config-dir\.appsody-config.yaml

# Change the entry home: to C:\my-appsody-config-dir

appsody run --config C:\my-appsody-config-dir\.appsody-config.yaml
```

Appsody version was 0.2.8.
