### ISSUE TITLE
Monthly project update - August 2019

### ISSUE THREAD

**Issue by sympatheticmoose** [appsody/website#194]
Write a blog post on the Appsody Medium account which summarises the progress made in the project and gives info on what's coming up.

I'll add bullet point items to this description, but please feel free to comment with any significant changes.

**Comment by neeraj-laad** [comment]
Sounds like a good idea and will be a good place for anyone to see how the overall project is progressing.. Today this information is scattered in individual repos.

**Comment by paulrobinson** [comment]
A Quarkus stack was contributed :-)

**Comment by sympatheticmoose** [comment]
Live - https://medium.com/appsody/appsody-in-autumn-project-update-2f89bdca7d96
