### ISSUE TITLE
Add tutorials to Appsody.dev

### ISSUE THREAD

**Issue by sympatheticmoose** [appsody/website#195]
**Is your feature request related to a problem? Please describe.**
'Tutorial' content is currently only in Medium - which is good and helps us publicise the project - but I feel this would also be useful to house within appsody.dev/docs, so that folks already aware of Appsody can go beyond the 'quick start'.

**Describe the solution you'd like**
Using the content under medium.com/appsody as a starting point, create a set of tutorials with a consistent style/structure to include within our documentation.

**Describe alternatives you've considered**
Keeping all tutorials on Medium and providing link within Docs section. 
Extension to 'Using Appsody' section. 
Additionally - separate repo under github.com/appsody - perhaps something to consider if we want to create some workshops? 

**Additional context**
If we do this, we could consider changing /tutorials to point to our content on appsody.dev and add a /blogs menu item to take folks to Medium (which I personally believe would be a better solution) - we certainly require content on both.

**Comment by SueChaplain** [comment]
@ddunn2 @helenmasters - should we change this issue into an epic and start breaking down what is needed? There will be web dev work and content work, so perhaps we can put our heads together and figure out the steps/considerations needed so that we're in a good position to start in the New Year?

**Comment by helenmasters** [comment]
We want to move on this now and have made the decision to bring the tutorials into the appsody.dev website. What steps do we need to complete to do this:

1. We need to decide how to structure this addition in terms of the sidebar (and gain agreement on this)

2. The tutorials to move in are listed in #472 (we are also expecting a couple of new tutorials to be added). The tutorials need to be in Markdown files and to be edited and updated, if required, to match the current CLI functionality.

3. Add an "Adding a tutorial" section to the contributing guide under the new "Adding a blog" section

**Comment by helenmasters** [comment]
Item 1 was discussed this morning, we came up with 3 options:

a) Create a tutorials page containing tiles similar to the blogs page (but without the latest in double width at the top). Link to this from a new item called **Tutorials** in the navbar. 

b) Replicate the size and style of the "Appsody Docs" text in the sidebar on the [docs page](https://appsody.dev/docs) below the user docs, call it "Appsody Tutorials" or "Appsody Scenarios" and put the individual tutorials as individual menu items underneath.

c) Create a new sidebar entry called Tutorials and put the individual tutorials as individual manu items underneath.

There was a preference expressed for item a), however, @KyeMaloy97  please can you roughly size the webdev work required for a), b) and c)?

**Comment by KyeMaloy97** [comment]
Just my two cents on the timeframe required for each:

a) This will be the best option but will take the longest. I would estimate it taking about a week, if not maybe a little less depending on how easily the components slot into a new page and how the tutorials translate into markdown.

b) This would be quicker to start but styling the Appsody Tutorials part is where this one may get complex as I dont think the header acts as a usual item in the sidebar as I never anticipated it getting different headers. I'd guess it would take 3 days tops if the tutorials need minimal tweaks and styling changes

c) Similar to B but a little less time as the work is easily done and the sidebar can have a new twisty added very easily. Probably 2 days

**Comment by SueChaplain** [comment]
With our current web dev workload, let's go for (a) for a basic page and think about adding filters as a  subsequent feature?

**Comment by neeraj-laad** [comment]
Closing this issue. We have a tutorials page live and we have separate issues for each tutorial so we can track them individually there.
