### ISSUE TITLE
Document app deploy configuration requirements for stack providers

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/website#198]
**Is your feature request related to a problem? Please describe.**
We have introduces application deployment configuration that should be added to the stack to leverage Kubernetes deployment capabilities from appsody operator, but this is not documented clearly for stack providers.

**Describe the solution you'd like**
A clear and concise description of what stack providers need to create and how it will be consumed.

**Comment by mhamwala** [comment]
We should add information about `config/app-deploy.yaml` to the [stack structure](https://appsody.dev/docs/stacks/stack-structure) with this PR

**Comment by neeraj-laad** [comment]
We are looking to not have app-deploy.yaml in the stacks. Closing this issue.
