### ISSUE TITLE
Clarify the graduation process for stacks (i.e. experimental->incubating->stable)

### ISSUE THREAD

**Issue by henrynash** [appsody/website#199]
It is not clear how a stack should graduate from experimental -> incubating -> stable. What are the criteria? How does one apply? Who decides? etc.

**Comment by mhamwala** [comment]
Thanks for raising an issue for this! @henrynash

cc: @appsody/dev

**Comment by henrynash** [comment]
This is probably also dependant on the answers to https://github.com/appsody/stacks/issues/265
