### ISSUE TITLE
Docs: Update stack structure docs

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/website#202]
Update stack structure docs along with creating and modifying stack docs to include the following recent changes:

- location of the license file

**Comment by Kamran64** [comment]
Speaking of, should the stack structure doc include ```image/config/app-deploy.yaml``` - Or are we leaving it out since it's not mandatory at this point?

**Comment by tomleah** [comment]
We could add `app-deploy.yaml` in the stack structure but we currently don't have docs on how to create this file. Maybe this could be contained in https://github.com/appsody/website/issues/198?

**Comment by tomleah** [comment]
Happy with either, I just don't want this to be lost when #207 is merged

**Comment by mhamwala** [comment]
+1 for adding this with 198,
I'll add a comment to the PR so that we have got it written somewhere

**Comment by tomleah** [comment]
Thanks @mhamwala, will link this to #207
