### ISSUE TITLE
Guidance on extending Appsody

### ISSUE THREAD

**Issue by ykoyfman** [appsody/website#205]
@tomleah As we discussed in Slack - it would be good to have specific documentation on 
- when to extend appsody for different scenarios
- mechanisms to control what a developer can change or override when working with an existing stack/template
- how appsody enforces specific technology choices

**Comment by tomleah** [comment]
Thanks for raising this @ykoyfman 🙂 

I agree, we should be clear on when it is appropriate to create a new stack, modify an existing stack and when to inherit from another stack. The same goes for templates with creating and modifying.

I believe we have some of this documentation already so I'm hoping part of this will be to revisit layout and flow to make these scenarios clear.

**Comment by helenmasters** [comment]
This issue should be looked at as part of #388

**Comment by neeraj-laad** [comment]
We believe this is addressed in new stack documentation. Closing. Please feel free to reopen if there is still an issue here.
