### ISSUE TITLE
Introduce filters for stack tiles on the homepage

### ISSUE THREAD

**Issue by Kamran64** [appsody/website#216]
**Is your feature request related to a problem? Please describe.**
With the addition of more stacks, the website [homepage](https://appsody.dev) has started to become cluttered with stack tiles. I think it would be nice to have filters depending on a stack's status (Experimental, Incubator, Stable).

Similar to @mdenby's suggestion: 
![image](https://user-images.githubusercontent.com/45264227/64116646-d12bcb80-cd8a-11e9-8d53-c465ba0fe49d.png)

As there are currently no stable stacks, instead of a blank screen when clicked, there could instead be a message notifying the user of this.

This would also serve as a fix to: https://github.com/appsody/website/issues/83

**Comment by ddunn2** [comment]
Closing this issue as work is being tracked here: #384
