### ISSUE TITLE
Doc fix: The APPSODY_PROJECT_DIR var is not a shell var

### ISSUE THREAD

**Issue by kylegc** [appsody/website#228]
**Describe the bug**
In the document https://github.com/appsody/website/blob/master/content/docs/stacks/environment-variables.md the APPSODY_PROJECT_DIR variable is under a section called "Appsody Shell Variables" but it should not be. It should be in the table above with all the other Appsody Environment Variables

**Comment by kewegner** [comment]
Kyle would this work?  I can make the change if it is OK?

| ```APPSODY_PROJECT_DIR```        | This variable allows override of the project directory while running  ```appsody extract, appsody build or appsody deploy```.                                              | ``` APPSODY_PROJECT_DIR=/<my-project-directory>```                              | /project      |
