### ISSUE TITLE
Improve how users discover Appsody stacks

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/website#231]
This epic should look to address a number of concerns around how we present the stacks to users and how they can find the stack they are after.

 - We have a growing list of stacks that are making the website home page longer. Especially on mobile view, we end up scrolling through the list.

- We need a mechanism to clearly state which stacks are experimental vs incubator (and stable)

**Comment by Kamran64** [comment]
I think we need to have some discussion on differentiating between stable, incubator and experimental stacks and defining what these terms actually mean. Maybe we should write up some criteria?

**Comment by mdenby** [comment]
Hopefully, this is the correct issue to post this in--here is a design for the Stacks page that allows for filtering. 

There is room at the top of the page to explain what stacks are, and when each type of stack is selected information about 'Cloud Packaged' etc could also be at the top of the page. 

Stack level--I'm not sure if this is the right term--any thoughts? Also, I have a tooltip to explain further what stable, incubator, and experimental mean. I don't think the user will need to constantly refer to that info (and those words are descriptive already). 

Is there someone that I need to work with on copy?

![Stacks](https://user-images.githubusercontent.com/26823018/68969196-6814fb00-07b2-11ea-9398-8a219083d7d2.jpg)

**Comment by helenmasters** [comment]
Now that the new [Stacks page](https://appsody.dev/stacks/) is live on the appsody.dev website, what is preventing this issue being closed?

**Comment by neeraj-laad** [comment]
All done. Closing for now.
