### ISSUE TITLE
broken link in create.md

### ISSUE THREAD

**Issue by alohr51** [appsody/website#241]
**Describe the bug**

In [create.md](https://github.com/appsody/website/blob/master/content/docs/stacks/create.md) the link below is broken.

"You now have the basic [structure](/docs/stacks/stack-structure) of a stack ready to create an Appsody stack."

**Comment by bschrammIBM** [comment]
The following links are broken:
https://github.com/appsody/website/blob/master/docs/stacks/stack-structure
https://github.com/appsody/website/blob/master/docs/stacks/environment-variables
https://github.com/appsody/website/blob/master/docs/stacks/build-and-test
