### ISSUE TITLE
Document usage of APPSODY_MOUNT_HOME to override home dir in mounts

### ISSUE THREAD

**Issue by chilanti** [appsody/website#249]
**Is your feature request related to a problem? Please describe.**
In some circumstances, the developer might be interested in overriding the resolution of `~` during the mount phase of `appsody run` - for instance, to overcome permissions limitations on the actual home directory on Windows 10 with Enterprise AAD. The `APPSODY_MOUNT_HOME` env var can be set by the developer to achieve that purpose, but its existence and usage is not documented.

**Describe the solution you'd like**
Document the usage and effects of setting `APPSODY_MOUNT_HOME`

**Additional context**
This variable was introduced to accommodate Codewind requirements - but it can be used to work around permission issues on the actual developers' home directory. This becomes particularly useful with the Java stacks, since they attempt to mount the user's `~/.m2/repository`. On Win 10 with Enterprise AAD, the user identity under which the container runs has no access to the developer's home - and the developer has no simple way to give permissions on the home directory to locally defined users. A way around this situation is to let the Appsody container mount the Maven repo on a different directory.

**Comment by chilanti** [comment]
Related to #147

**Comment by sympatheticmoose** [comment]
I would like to revisit how we use this... but agreed for now we need to doc the current implementation to help with ^
