### ISSUE TITLE
document use of --knative flag on appsody deploy

### ISSUE THREAD

**Issue by kewegner** [appsody/website#250]
We need to document this in the build and deploy document.

The documentation must discuss the following:

If the --knative flag is present and there is a app-deploy.yaml containing an appsodyapplication, the createKnativeService: true tag will be added to the yaml file if not present.

If the --knative flag is not present and createKnativeService: true is in the app-deploy.yaml file the createKnativeService element will be removed. if it is createKnativeService: false, it will remain.

If the stack does not contain an app-deploy.yaml file containing and appsodyapplication, the --knative flag will have no impact.

Unless the appsody deploy is done with a --tag, -t option the imagename will be prefixed with dev.local/

**Comment by sympatheticmoose** [comment]
related to https://github.com/appsody/appsody/issues/303
