### ISSUE TITLE
APPSODY_WATCH_REGEX is insufficiently documented

### ISSUE THREAD

**Issue by BarDweller** [appsody/website#251]
**Describe the bug**
It's unclear from the current documentation how to correctly code anything beyond simple regex's for the `APPSODY_WATCH_REGEX` env var content. 

Eg. Given a change to `src/main/test.sh` living in the container at `/project/user-app/src/main/test.sh` where the `/project/user-app` is the home dir for the project.. what string is being matched against for the regex ? is it `test.sh`, `src/main/test.sh` or `/project/user-app/src/main/test.sh` ? 

The documentation should also state which regex syntax is in use, there are many. I'm assuming go, because I know the controller is written in that, but it's not documented as such, and other regex syntaxes are more common & popular.

**Comment by sympatheticmoose** [comment]
@neeraj-laad can you describe what we need to add here and then we can pass to someone else?

**Comment by neeraj-laad** [comment]
I think we should document a number of aspects along with relevant examples for stack providers to understand this better:

- Explain what is the regex going to be tested against (full path in the container, the path within the watch dir, only file name). Some examples here will be helpful.
- Clearly articulate what is allowed and what is not allowed in this regex.
- Briefly explain how the appsody watcher deal with file changes, and how stack creators can use some other variables to get optimum file watching experience - watch dir, watch interval, watch ignore dir etc.
