### ISSUE TITLE
Clarify the APPSODY_PREP is not run before ON_CHANGE events

### ISSUE THREAD

**Issue by henrynash** [appsody/website#262]
Our current docs (on stack variables) for APPSODY_PREP starts with:

`This is an optional command executed before the APPSODY_RUN/TEST/DEBUG and APPSODY_RUN/TEST/DEBUG_ON_CHANGE commands are run. 
`

This is somewhat confusing, and implies that APPSODY_PREP is run before each CHANGE event - which is not the case. It is only run on APPSODY_RUN/TEST/DEBUG.

**Comment by kylegc** [comment]
Duplicate of #268
