### ISSUE TITLE
An "Appsody Flow" diagram would really help

### ISSUE THREAD

**Issue by henrynash** [appsody/website#273]
A picture tells a 1000 words....and one that shows the flow from appsody init -> deploy would be a useful additional to the overview.

**Comment by Kamran64** [comment]
I think we have a rough flowchart somewhere in a box note... @neeraj-laad? Could do with some updating though.

**Comment by henrynash** [comment]
I was thinking of something a bit more "pretty"....see PR...

**Comment by neeraj-laad** [comment]
Yes, I'd like to get a prettier picture over, perhaps get the designers involved in creating that for us.

**Comment by helenmasters** [comment]
@ddunn2 please can you work with Melissa on this, as I do think that this would be a useful addition to the website?

**Comment by henrynash** [comment]
@helenmasters @ddunn2 @neeraj-laad So I proposed an actual diagram in the PR addressing this issue (https://github.com/appsody/website/pull/274) but totally happy if an alternative would be better.

**Comment by ddunn2** [comment]
Unless I'm missing something within the website, Images within Markdown currently won't work. I've cloned your branch and tested this, the image doesn't load within the website.

It seems the Markdown plugin the website uses doesn't handle images by default so if we're looking to add images to the docs (which I think is a great idea) then this is an issue that needs addressing. 

As for the image itself we should certainly try to make it prettier :). I'll see if we can get some help with that.

**Comment by henrynash** [comment]
Ah, hmm, yes that is a problem (although I think there are other .png images display already by the website - so maybe I didn't put it in the right place :-) ).

FYI, when I said "make it prettier", the diagram I included was created from scratch as an attempt to "be pretty" :-). However, I'm no great diagram maker...so happy for someone to improve on it if it needs it!

**Comment by neeraj-laad** [comment]
Reopening this issue as we need to:

- fix the website (gatsby plugins etc) to be able to display the image
- get designers review / amend / prettify the flow diagram

**Comment by ddunn2** [comment]
I've just enabled images in Markdown on another website I'm working on, so I'll look at porting that fix over to the Appsody site soon. 

We should also consider adding guidelines around how contributors would add/edit the docs.

**Comment by neeraj-laad** [comment]
@ddunn2 now that we have this capability, Can we please re-implement #274 ?

**Comment by neeraj-laad** [comment]
Closing this issue as we have the image for flow diagram on our website now
