### ISSUE TITLE
Question: relation between dockerfile-stack and dockerfile

### ISSUE THREAD

**Issue by sympatheticmoose** [appsody/website#277]
From slack, someone creating a new stack - "what is the relationship between the Dockerfile-stack and the project/Dockerfile in a stack definition.  in particular, each is used to create a docker image, one for the stack and the other for an app that the stack builds"

**Comment by neeraj-laad** [comment]
@helenmasters is this something that will be addressed by the `Glossary` section you are working on?

**Comment by helenmasters** [comment]
@neeraj-laad the `Glossary` will hopefully help, but we also need to add further clarification where we're currently talking about these terms in the stack structure as it doesn't sound like it's clear at the current time. I'll take a look at both.

**Comment by helenmasters** [comment]
Referencing #388 as this can be revisited as part of that work. The terms should also be in the glossary imminently...

**Comment by helenmasters** [comment]
First part of the 'fix' here is complete as these terms are now in the Glossary.

**Comment by CameronMcWilliam** [comment]
We believe this is now clear thanks to the Glossary and the references in #395
