### ISSUE TITLE
Create a prototype Glossary page

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#282]
The task here is to design and create a prototype Glossary page which can then be populated with words and associated definitions from #272.

**Comment by KyeMaloy97** [comment]
The page has been made, but is waiting on the definitions to be written up by Helen and David.

**Comment by helenmasters** [comment]
Kye, below are the first set of agreed definitions for the Markdown file:

Appsody CLI

The Appsody command-line interface supports the full application development lifecycle; creating stacks, creating applications based on stacks, testing and debugging your applications, and deployment to Kubernetes.

Project template

Project templates provide a starting point, typically a 'Hello World' application, for application development. Like other components within an Appsody stack, you can customize project templates and share them across teams.

**Comment by helenmasters** [comment]
A second set which may require minor tweaks:

Dockerfile

`Dockerfile` combines your application and the stack to build a production image, ready for deployment. For more information on Dockerfiles see the official [Docker documentation](https://docs.docker.com/engine/reference/builder).

Dockerfile-stack

`Dockerfile-stack` is a Dockerfile that builds a stack container image used during development. For more information on Dockerfiles see the official [Docker documentation](https://docs.docker.com/engine/reference/builder).

**Comment by KyeMaloy97** [comment]
Currently working on recreating this page, have successfully added MDX support to the website which is future proofing and learning how to make the components as easy as possible to add to (so new definitions are easy to put in and require no advanced knowledge).

**Comment by KyeMaloy97** [comment]
Have a working version, which allows you to write all of the code in Markdown :)

<img width="1680" alt="Screenshot 2019-12-03 at 12 41 35" src="https://user-images.githubusercontent.com/24469095/70052056-5745f100-15ca-11ea-83f0-ff73600b7e97.png">

**Comment by SueChaplain** [comment]
I like the pink one!

**Comment by KyeMaloy97** [comment]
All the corners rounded or just the ones on the right? If you round all the corners the left border gets cut off at the top and bottom like this: 

## All Rounded Corners
<img width="1680" alt="Screenshot 2019-12-03 at 13 03 50" src="https://user-images.githubusercontent.com/24469095/70053434-5c586f80-15cd-11ea-90ad-45abbf22086a.png">

This is how it looks with the left corners squared off:

## Square Corners
<img width="1680" alt="Screenshot 2019-12-03 at 13 04 27" src="https://user-images.githubusercontent.com/24469095/70053487-76924d80-15cd-11ea-8f37-63a0113daac9.png">

**Comment by helenmasters** [comment]
I prefer the design of A and the colours of B. The bit I like on A is the curved box design rather than the pink bar on the left, the bit I like on B is the background pink colour.

**Comment by KyeMaloy97** [comment]
Okay, well here it is with the colours but rounded: 

## Colours and Rounded
<img width="1680" alt="Screenshot 2019-12-03 at 13 32 22" src="https://user-images.githubusercontent.com/24469095/70055424-6d0ae480-15d1-11ea-9356-dacb26ef0028.png">

and here it is with more of a boxy shape, and the thicker border on the side:

## Boxier with thick border
<img width="1680" alt="Screenshot 2019-12-03 at 13 28 28" src="https://user-images.githubusercontent.com/24469095/70055496-8b70e000-15d1-11ea-9fe3-cb10cd208527.png">


and finally boxier with no extra borders, very similar to a blockquote though:

## Boxier with thick left border and no extra borders
<img width="1680" alt="Screenshot 2019-12-03 at 13 21 45" src="https://user-images.githubusercontent.com/24469095/70055553-aa6f7200-15d1-11ea-801a-39e6005dd1f3.png">

**Comment by SueChaplain** [comment]
I like colours and rounded best, but they all look pretty good!

**Comment by KyeMaloy97** [comment]
PR is open, however the CLI reference is broken if we merge at the moment due to their variables looking like React elements, and therefore MDX (also introduced in this PR) gets upset and refuses to render the page. Raised an issue in Appsody (https://github.com/appsody/appsody/issues/761).
