### ISSUE TITLE
Document the "new flow" of Appsody for stack creators

### ISSUE THREAD

**Issue by Kamran64** [appsody/website#291]
**Is your feature request related to a problem? Please describe.**
After the ```appsody stack create``` command is added (PR here: https://github.com/appsody/appsody/pull/392), we will have a new flow for stack creators to contribute stacks. Rather than manually creating files/folders and running the build script they have the option to use ```appsody stack create```, ```appsody stack package```, ```appsody stack lint```, and then ```appsody stack validate``` to test and run their stack.

**Describe the solution you'd like**
As such, I think the `Creating Stacks` page and `Building and Testing Stacks` page could be updated. https://github.com/appsody/website/pull/263 aims to document the new `stack package` command but we could have more written about the other commands outside of the CLI reference doc.

**Additional context**
We should wait until https://github.com/appsody/appsody/pull/392 is put into a release before documenting the `stack create` command but work can be done in advance.

**Comment by neeraj-laad** [comment]
I believe the flow could be described as follows:

- create a stack
- modify the stack
- validate the stack changes
- package the stack
- publish the stack

We can start documenting individual steps with new cli capabilities as they become available.

**Comment by helenmasters** [comment]
@neeraj-laad can I close this issue now as we've got the basis of this done now, there's just publishing to add?

**Comment by neeraj-laad** [comment]
I'd wait for publishing to be added to the website before closing.

**Comment by helenmasters** [comment]
Closing now a publishing page has been added to the website.
