### ISSUE TITLE
Need to have live Appsody Twitter Account tweets or advertising upcoming events, videos, blogs and more

### ISSUE THREAD

**Issue by dionj** [appsody/website#292]
**Is your feature request related to a problem? Please describe.**

Problem Statement: "As a developer, I have no ideas about where to find experts to have a 1x1 opportunity on how to engage further.  Perhaps contents, events, videos or more."

Solution Proposal: perhaps we need the Appsody website to have live Appsody Twitter Account tweets or advertising upcoming events, videos, blogs and more to amplify the developers' engagements and where to find us for the next conversation. 

**Describe the solution you'd like**
Social media includes events and updates so developers can know where and when to meet our experts to chat more.  

**Describe alternatives you've considered**
Rolling live tweet like Kabanero.io  and/or adding highlight of event activities to encourage further developers' engagement. 

**Additional context**
N/A

**Comment by neeraj-laad** [comment]
@dionj Thanks for raising this issue. 

@appsody/content Do we have any plans to address some or all of the ideas suggested here?

**Comment by SueChaplain** [comment]
We discussed this briefly this morning and agreed that these were good ideas - something to discuss initially with design.

**Comment by dionj** [comment]
If you want to a good example - Kabanero.io is now currently tweeting live at the bottom portion of their own website.  perhaps you can reach Andrew Lohr's team.  https://kabanero.io/

**Comment by dionj** [comment]
I have emailed the OM of Appsody David Harris to check his input on this issue.

**Comment by ddunn2** [comment]
I also think this would benefit from further discussion. 

On kabanero.io the tweets are at the bottom of the home page, so a user would have to scroll right to the bottom of the page to even be aware it exists. Assuming they find it, the latests tweets may not actually be related to events/content/videos as Appsody tweets/retweets various things. 

They're just a couple of concerns I have with using a live Twitter feed as an 'advertising' tool

If our aim is to better advertise events, videos etc etc there may be other ways to achieve that, so as @SueChaplain mentioned, we should have a design discussion around this :)

**Comment by sympatheticmoose** [comment]
Thanks @dionj for the suggestion, I can understand how a feature like this makes sense for a project like Kabanero, and potentially Appsody. I personally think, however, this is a **future** enhancement, and not a _priority_ at this stage. I agree with @ddunn2 that we should discuss alternatives, and do this as much as we can in the open/at least document and discussion points.

What I think we need to focus on before highlighting our twitter on Appsody.dev is, and would provide more value from folks limited time:
- building out our content, identifying gaps in current content, and improving quality/usability of our content. This is a top priority for me, and so important to help folks use and discover Appsody. We're very lucky to have @SueChaplain , @helenmasters and others starting to look at this with us.
- open meetings / working hours - as mentioned in a blog post recently - once we establish other ways for people to engage with the core team and to learn more, we can look at promoting them.
- generally improving the discovery of Appsody - this spans content/social/events strategy - and does tie into just 'better use of Twitter' - which I know is something I want to take a look at. Once we're doing that, we would want to integrate twitter more into the site.

**Comment by sympatheticmoose** [comment]
> As a developer, I have no ideas about where to find experts to have a 1x1 opportunity on how to engage further

Slack ;)

**Comment by dionj** [comment]
@sympatheticmoose understood. Agreed!  :-)  You are the OM for this open-source project, so I trust your judgment.  Slack is awesome! Love Slack! However, the opportunity of having a face-to-face discussion with experts at the conference save thousands of words. It brings distance closer between people to people. I will leave this to you to prioritize. The easier to bring values to developers/architects/tech leads, the better to bring them to adopt and contribute.  Whatever the tooling or mechanism we can use to achieve the same successful goals. Thank you @sympatheticmoose and the entire team for the excellent work you have done with the Appsody project so far.  👍 @sympatheticmoose, you can feel free to close and comment on this issue.

**Comment by sympatheticmoose** [comment]
I'm just trying to help the project like any collaborator, so I'm just sharing my view here :) I am more than happy to discuss this further or for others to weigh in - the project owns its future. Whilst I wholeheartedly agree on the value of conferences, that is a small audience compared to self-service discovery. Our collaborators can't get to every event, nor can any developer - so trying to ensure quality of content and providing access to experts through slack/zoom/whatever is really important

**Comment by gcharters** [comment]
I think there are a number of different items in this single issue that should be considered independently.  For example, I would prioritize the twitter feed idea fairly low down.  We want to use twitter to attract people to appsody.dev, actually having the tweets on the site is less valuable, IMO.  However, I think having a blog on the site would be very valuable as it can be used to share the latest news/developments with Appsody users.  @sympatheticmoose - can we consider adding a blog to the site separately.  E.g. something like https://openliberty.io/blog/

**Comment by sympatheticmoose** [comment]
I think we're heading towards adding a blog capability on the site and we'll leave it at that for now.
