### ISSUE TITLE
Remove `gatsby-plugin-layout` from website

### ISSUE THREAD

**Issue by ddunn2** [appsody/website#296]
Currently the Appsody website uses the `gatsby-plugin-layout` which reverts Gatsby to its V1 behaviour when dealing with layout components however there is no reason for the website to be using it. 

Removing this plugin will:
- Tidy up the codebase
- Make future work easier
- Make no change to the visual elements on the website

This will simply set the groundwork for future items we need to address.

**Comment by sympatheticmoose** [comment]
thanks for raising @ddunn2
