### ISSUE TITLE
Add consistency to mobile navbar

### ISSUE THREAD

**Issue by ddunn2** [appsody/website#297]
**Is your feature request related to a problem? Please describe.**
Currently when viewing the website on mobile there is 2 different navbars, one for the home page and another for the docs page. Both of these navbars have a hamburger menu which do different things. 

We should find a way of making this a little more consistent, and having the navbar be the same for all pages. 

**Describe the solution you'd like**
Convert the navbar into a mobile friendly variant, that is having the navigation at the bottom of the screen where a users thumbs are. This behaviour is inline with how modern apps work and feels more natural to mobile users, as opposed to having to stretch (if using with one hand). 
The hamburger menu could also be brought down to the bottom so it's easier to reach for a user.

**Comment by KyeMaloy97** [comment]
Opened a PR here #316

**Comment by KyeMaloy97** [comment]
Merged into master.
