### ISSUE TITLE
Improve the clarity of interactive elements 

### ISSUE THREAD

**Issue by ddunn2** [appsody/website#298]
**Is your feature request related to a problem? Please describe.**
Currently there are a lot of interactive elements, (such as links, buttons etc) that a user can interact with but many of these do not have a real indication that you're about to interact with them. Currently only the cursor changes but we can improve the visual side of this. 

**Describe the solution you'd like**
When you hover over certain interactive elements, something happens to signify this element has been targeted, such as an on hover effect. For links this could be a simple colour change for example.

**Comment by KyeMaloy97** [comment]
PR opened and merged #304.
