### ISSUE TITLE
Add documentation on contributing guides

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#301]
We need to have doc on how to contribute guides, add pictures, perform local builds etc.

**Comment by ddunn2** [comment]
Currently these docs exist here: https://github.com/appsody/website/blob/master/DEVELOPMENT.md

We should update these docs to include adding images and possibly link to them from the contributing guide, or do something else to increase their visibility.

**Comment by KyeMaloy97** [comment]
Opened a PR #308 to address the issue of how a contributor adds images to our docs.

**Comment by neeraj-laad** [comment]
PR has been merged. closing this issue.
