### ISSUE TITLE
Installation instructions for binary installation do not cover "controller" install

### ISSUE THREAD

**Issue by nastacio** [appsody/website#303]
**Describe the bug**
The instructions for Linux users downloading their own binaries only list the need to download the appsody-controller under the "Installing on Ubuntu":
https://appsody.dev/docs/getting-started/installation/

Problem #1: Users for other Linux distros do not see that instruction and hit a blocking problem with `appsody run`, e.g.

```
appsody run
Running development environment...
Pulling docker image jpapejr/go-modules:0.3
Running command: docker pull jpapejr/go-modules:0.3
0.3: Pulling from jpapejr/go-modules
Digest: sha256:37620ec0435b828ec0ccc42c92df31a2a48d956f5537c385b60227b23cd63ecb
Status: Image is up to date for jpapejr/go-modules:0.3
docker.io/jpapejr/go-modules:0.3
[Error] Cannot find source file /root/toolbox/linux/appsody-controller to copy
[Error] Cannot retrieve controller - exiting: stat /root/toolbox/linux/appsody-controller: no such file or directory
```

**To Reproduce**

**Expected behavior**
The instructions for users downloading their own binaries should be clear for all users, regardless of environment.

**Actual behaviour**
The instructions only mention the need for downloading the appsody-controller under "Installing on Ubuntu"

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by nastacio** [comment]
This is a follow on to issue #140

**Comment by helenmasters** [comment]
@chilanti I presume that this issue can be shut now?

**Comment by helenmasters** [comment]
Closing as the controller isn't now installed as a separate binary.
