### ISSUE TITLE
Improve descriptions of how to combine --push-url, --pull-url and --tag to use private registries

### ISSUE THREAD

**Issue by henrynash** [appsody/website#338]
The new `--push-url` and `--pull-url` deploy options are great for private image repos (like OpenShift). However, it is not immediately obvious how to "divide up" the eventual image name & location you want across the `--push-url`, `--pull-url` and `--tag` 

Here's an example of a recent deploy to OpenShift (where I had already set DOCKER_REGISTRY to the route I created to access the OpenShift registry):

appsody deploy --tag insurance-quote/mytest:v1 --push-url $DOCKER_REGISTRY --push --pull-url docker-registry.default.svc:5000 --namespace insurance-quote

I think this is the right way to split it up - and if so, we should show this as best practice somewhere in the docs

**Comment by henrynash** [comment]
See also my CLI issue on the use of `--push` with `--push-url` : https://github.com/appsody/appsody/issues/568

**Comment by henrynash** [comment]
I'd be happy to push some docs for this

**Comment by helenmasters** [comment]
@henrynash if you have time to do that, that would be great. I totally agree that it's not at all obvious how to split up what you're trying to achieve across those flags.

@neeraj-laad can you take a look at the spilt and check that you agree with the example provided?

**Comment by EnriqueL8** [comment]
This has been addded in #433
