### ISSUE TITLE
Error in deploy documentation

### ISSUE THREAD

**Issue by kylegc** [appsody/website#348]
See slack thread: https://appsody.slack.com/archives/CKXDDB4A3/p1573033082005500

Doc https://appsody.dev/docs/using-appsody/building-and-deploying/#ensuring-the-latest-application-code-changes-get-deployed
"In order to ensure that the latest version of your app gets pushed down to the cluster, you have two options:
1. Remove the app, and re-deploy (appsody deploy delete and then appsody deploy)
2. Explicitly tag the image every time with a new tag, to force Kubernetes to take action (for example: appsody deploy -t dev.local/my-image:0.x, where you increment x every time you re-deploy)."

Step 1 does not work.

**Comment by kylegc** [comment]
@chilanti may have some ideas on this

**Comment by helenmasters** [comment]
@kylegc and @chilanti - do we have a suggested docs fix for https://github.com/appsody/website/issues/348? Is the temporary fix to remove option 1 from the docs for now, or something else?

**Comment by kylegc** [comment]
Closing, the docs have been updated
