### ISSUE TITLE
brew upgrade appsody does not work

### ISSUE THREAD

**Issue by DanielChuDC** [appsody/website#351]
## Summary
```sh
[Debug] Creating log dir .appsody/logs
[Debug] Logging to file /.appsody/logs/appsody2019-11-07T11-20-02.809248.log
[Debug] Writing config file /.appsody/.appsody.yaml
[Debug] Getting latest version https://github.com/appsody/appsody/releases/latest
[Debug] Got version 0.4.10
[Info] 
*
*
*

A new CLI update is available.
Please run `brew upgrade appsody` to upgrade from 0.4.7 --> 0.4.10.
```

### Scenario
1. When I run appsody -v , above log returned.

2. I follow the instruction to run `brew upgrade appsody` , but got error `Error: appsody 0.4.7 already installed`

### Actual output
`Error: appsody 0.4.7 already installed`

### Expected output
- Successful upgrade to 0.4.10

### Current situation
I had to `brew uninstall appsody` and `brew install appsody/appsody/appsody` to make upgrade version.

**Comment by CameronMcWilliam** [comment]
Hi @DanielChuDC,  I just did this exact upgrade `0.4.7` -> `0.4.10` and had no issues.  I'm on macOS Catalina 10.15.1.   What OS and version are you on?  As I just did this upgrade I don't think the issue lies with the command not working at all, it could be not functional on an older OS version etc.

**Comment by DanielChuDC** [comment]
Hi @CameronMcWilliam , Thank you for your reply! I'm on macOS Catalina 10.15.1 too. Not sure why the error trigger.

As I cannot reproduce or inspect the error. I will close the issue.
