### ISSUE TITLE
Document guidance for modifying stack

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/website#358]
We should update the modify stacks document to provide more details on what considerations a stack creator should make and how to go about them.

Proposing the following titles:

- Overview
  - stack.yaml
  - README.md

- Project templates

- Stack image for local development
  - Handling file mounts
  - Stack environment variables
  - Monitoring file changes
  - Managing dependencies
  - File Permissions
  - IDE Considerations
  - License

- Supporting application build and deployment

- Advanced topics:
  - Specifying requirements
  - Templating in stacks

**Comment by helenmasters** [comment]
@CameronMcWilliam is all of this covered in your pull request #395 or is there more to write for this?

**Comment by CameronMcWilliam** [comment]
merged with #395
