### ISSUE TITLE
Docs: revisit the Appsody flow diagram

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#366]
We should create a cleaner and clearer version of the Appsody flow diagram which is on the Appsody home page (appsody_flow.png).

**Comment by neeraj-laad** [comment]
@EnriqueL8 I would like you to create this flow diagram and then we can work with @KyeMaloy97 to prettify it and get it on the website.

**Comment by sympatheticmoose** [comment]
as mentioned https://github.com/appsody/website/issues/373 it would be good if this could be closed out asap

**Comment by KyeMaloy97** [comment]
Spoken with Enrique, and told him the tool to use to make the bare bones diagram that I can then work on prettying up and getting into the website

**Comment by sympatheticmoose** [comment]
@EnriqueL8 @KyeMaloy97 any progress on this?

**Comment by EnriqueL8** [comment]
We have booked a meeting tomorrow to finalise this

**Comment by helenmasters** [comment]
Closing as the new architecture diagram has been merged under PR #431.
