### ISSUE TITLE
Add Maven as a prerequisite

### ISSUE THREAD

**Issue by tellison** [appsody/website#37]
Initializing a java-microprofile project on a new system fails with `mvn: command not found`.

Maven should be installed with appsody, or listed as a prereq.

```
tellison@scw-appsody:~/test3$ appsody init java-microprofile
Running appsody init...
Downloading java-microprofile template project from https://github.com/appsody/stacks/releases/download/0.2.0/incubator.java-microprofile.templates.default.tar.gz
Download complete. Extracting files from java-microprofile.tar.gz
Setting up the development environment
Running command: docker[pull appsody/java-microprofile:0.2]
Running command: docker[run --rm --entrypoint /bin/bash appsody/java-microprofile:0.2 -c find /project -type f -name .appsody-init.sh]
Extracting project from development environment
Running command: docker[create --name test3-extract -v /home/tellison/test3/src:/project/user-app/src -v /home/tellison/test3/pom.xml:/project/user-app/pom.xml appsody/java-microprofile:0.2]
Running command: docker[cp test3-extract:/project /home/tellison/.appsody/extract/test3]
Running command: docker[rm test3-extract -f]
Project extracted to /home/tellison/test3/.appsody_init
Running command: ./.appsody-init.sh[]
[InitScript] ./.appsody-init.sh: line 2: mvn: command not found
[Warning] The stack init script failed: exit status 127
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.
```

**Comment by tomleah** [comment]
Appsody will still work in this case however, depending on your IDE the application may not build correctly. The `mvn` prereq is there to install dependencies locally so that the IDE's don't show red.

@tellison where would be best to document these prereqs? We currently only have the `[WARNING]`'s output from the CLI.

Do you expect there to be a "IDE Prerequisites" section on the [stack readme](https://github.com/appsody/stacks/tree/master/incubator/java-microprofile) from a user's point of view?

**Comment by neeraj-laad** [comment]
@tellison Would adding the following lines to the README for this stack make it clearer:

*Note:* This stack recommends you to have Maven installed on your system for best IDE experience. If you do not wish to do so, please ignore the warning message during `appsoy init`. You can still use Appsody for your application development as Maven will be provided by the Appsody container.

**Comment by tellison** [comment]
Ok, maybe it just needs clarification in the warnings messages.

For example, it would be good in this instance if you could suppress the failure message in:
```
[Warning] The stack init script failed: exit status 127
```
Which I thought meant that there had been an error in the Appsody script itself.

Then:
```
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.
```
In this warning it says the container *should* still work, and your comments above say it *will* work.

Having some text as @neeraj-laad suggests in the pre-reqs listed on the website would be helpful too.
