### ISSUE TITLE
Create an Appsody Architectural Overview Content

### ISSUE THREAD

**Issue by dewan-ahmed** [appsody/website#373]
**Is your feature request related to a problem? Please describe.**
Anyone new to project Appsody would like to know how different pieces of Appsody fits and plays together. Also, it is important to know how Appsody interfaces with Docker.

**Describe the solution you'd like**
An architectural diagram showing different pieces of Appsody engine. If possible, an explainer video on this would be even more helpful.

**Describe alternatives you've considered**
Diagram available on https://appsody.dev/docs.

**Additional context**
Not applicable.

**Comment by Kamran64** [comment]
Thanks for raising this @dewan-ahmed - At one point we did have an Appsody flow diagram to showcase a more "architectural" view of the project. We've reopened an issue on that here https://github.com/appsody/website/issues/366, but I agree that a video might be a bit more accessible to a new user.

**Comment by sympatheticmoose** [comment]
I agree this would be a nice addition to our content and help users understand the mechanics of Appsody, including things like the controller. If we use this issue to storyboard a video - that may inform other changes we want in the docs or in a separate article/blog.

Perhaps we could prioritise #366 and try to get that closed out in the next sprint as that will help efforts here.

**Comment by SueChaplain** [comment]
@sympatheticmoose - Please outline the content for the video so we can determine whether this is something the content team can work on.

**Comment by helenmasters** [comment]
Closing as the wording has been added under PR https://github.com/appsody/website/pull/492 and the architecture diagram has been added under PR https://github.com/appsody/website/pull/431.
