### ISSUE TITLE
Improve SEO for docs using keywords

### ISSUE THREAD

**Issue by ddunn2** [appsody/website#378]
With the merge of #340 each page on the website can provide unique titles for the meta data relating to SEO. 

With this we can also enable keywords to be provided for each page. These keywords could be provided via the frontmatter in each document, the inclusion of these keywords could be optional.

**Comment by KyeMaloy97** [comment]
Keywords are dead according to Bing and Google, here are some posts that show they both do not take them into account when ranking pages:

### Google
https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
### Bing
https://blogs.bing.com/webmaster/2014/10/03/blame-the-meta-keyword-tag
