### ISSUE TITLE
Support styling for bullet points

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/website#387]
**Describe the bug**
Bullet points have no styling on the website.

**To Reproduce**
Make a list using `*`.

**Expected behavior**
Bullet pointed list to appear.

**Actual behaviour**
Paragraphed text with no spacing.

**Additional context**
Can see this on the stack structure page currently.

**Comment by skoh7645** [comment]
You can also see this at https://appsody.dev/docs/using-appsody/cli-commands/#appsody-stack-validate

**Comment by KyeMaloy97** [comment]
Opened a PR to resolve the issue #389

**Comment by helenmasters** [comment]
Closing the issue as the PR is now merged and the fix is visible on https://appsody.dev/docs/using-appsody/cli-commands/#appsody-stack-validate and within the stack structure page.
