### ISSUE TITLE
Restructuring stacks documentation

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#388]
@CameronMcWilliam 
Please can you revisit the docs flow from create -> modify -> package -> validate -> publish within the stacks documentation to make sure it makes sense for users. Note that there is still content to be written for the modifying stacks page under #358.

As part of this work please can you also revisit the Stack Structure and Stack Overview pages. I recommend creating a set of titles for the content we'd like on both of those pages so that we can review the content with Neeraj before writing those pages.

**Comment by CameronMcWilliam** [comment]
# Restructuring stacks documentation

Work in progress, several PR's will go into this issue:

- Stacks Overview/Stacks structure
- Creating stacks/Modifying stacks
- Packaging stacks
- Testing stacks
- Publishing stacks

## Key ideas

- Improve workflow of stacks
- Squash creating and modifying into one developing stacks section 
- Reduce repeated information across pages
- Adding expandable advanced section in pages
- Clean up typos and misinformation

**Comment by CameronMcWilliam** [comment]
Completed with merge of #395
