### ISSUE TITLE
Remove reference to controller bind mount

### ISSUE THREAD

**Issue by chilanti** [appsody/website#393]
**Describe the bug**
The docs still have a reference to the controller bind mount.

The controller is now being downloaded by the CLI and mounted in a Docker volume (you will see Docker volumes being created - named , for example, `appsody-controller-0.3.1` where `0.3.1` is the version of the controller that Appsody is currently using), so this reference to a bind mount needs to be removed.

**Comment by helenmasters** [comment]
Closing the issue as the docs have now been merged.
