### ISSUE TITLE
Expandable advanced section

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/website#398]
**Is your feature request related to a problem? Please describe.**
Some docs have, or will have, advanced sections on the page, and as a result can cause the page to feel quite bloated.

**Describe the solution you'd like**
Having the option to include an expandable advanced section at the bottom of pages would allow information of higher detail to be presented without overloading newer users and preserving work flow through pages.

**Comment by helenmasters** [comment]
Do we still have a requirement for this @CameronMcWilliam?

**Comment by CameronMcWilliam** [comment]
Don't see a need for this atm.
