### ISSUE TITLE
Document process to preview Changes for website

### ISSUE THREAD

**Issue by kewegner** [appsody/website#40]
It will be useful to have documentation on how to test documentation changes (generated or manual) for their effect on the website.

**Comment by mhdawson** [comment]
+1

**Comment by tomleah** [comment]
Top of my list :) Let's start with how to preview these docs locally and then https://github.com/appsody/website/issues/48 should let us pull in docs from a fork alongside https://github.com/appsody/docs and see how all the docs fit together
