### ISSUE TITLE
Update Favicon on website

### ISSUE THREAD

**Issue by mdenby** [appsody/website#410]
@ddunn2 I noticed the favicon on the website looks super pixelated. I've  created a new favicon and attached a zip file with the files here.
[https://app.zenhub.com/files/192303752/ae09e534-809f-4c67-ba89-8d8bad358ff2/download](https://app.zenhub.com/files/192303752/ae09e534-809f-4c67-ba89-8d8bad358ff2/download)

**Comment by ddunn2** [comment]
Thanks for creating this for us @mdenby 👍 

We'll get it updated today!
