### ISSUE TITLE
code whitespace not being respected

### ISSUE THREAD

**Issue by ebullient** [appsody/website#42]
The whitespace in code blocks isn't being respected in the rendered site.

For example, https://appsody.dev/docs/stacks/create-or-modify looks like this: 

> ![image](https://user-images.githubusercontent.com/808713/60289630-de3cc200-98e4-11e9-8ee5-65c94f070d8b.png)

The github-rendered markdown, however, looks like this: 

> ![image](https://user-images.githubusercontent.com/808713/60289664-f6144600-98e4-11e9-960a-70c175bd2656.png)

https://github.com/appsody/docs/blob/master/docs/stacks/create-or-modify.md

**Comment by tomleah** [comment]
Thanks for spotting this @ebullient 🙂Looks inconsistent with the rest of the documentation so will take a look at this asap
