### ISSUE TITLE
Document new `stack-registry` flag

### ISSUE THREAD

**Issue by skoh7645** [appsody/website#421]
With the addition of the new `stack-registry `flag (the primary use case being the `appsody init` command), we should document this on the [Initializing Appsody Projects](https://appsody.dev/docs/using-appsody/initializing-project) webpage with the new CLI release. 

Related to: https://github.com/appsody/appsody/issues/696

**Comment by helenmasters** [comment]
Assigning to myself as we're getting closer to merged the associated PR. I'll draft some words to add. I think we need something along the lines of:

"You can specify the `--stack-registry` flag to override the default registry URL that hosts your stack images, from the default value “docker.io”. Subsequent calls to Appsody CLI commands, such as `appsody run`, then use this registry URL."

I'm unsure if we need to add the detail about where this information is stored in the user documentation:

"Specify the --stack-registry flag to override the default registry URL that hosts your stack images, from the default value “docker.io”. The registry URL is stored in the `stack` element of the `.appsody-config.yaml` file so subsequent calls to Appsody CLI commands, such as `appsody run`, then use this registry URL by default."

I have a few questions about how this has been implemented so I'll add those to https://github.com/appsody/appsody/issues/696
