### ISSUE TITLE
Consider line wrapper to avoid scrolling

### ISSUE THREAD

**Issue by mhdawson** [appsody/website#43]
Looking at https://appsody.dev/docs/using-appsody/building-and-deploying in 2 different browsers, even if I shrink my font quite small it still requires scrolling left and right for each line  to be able to read the text.

Consider updating the line lengths etc. to make  it easier to read.

**Comment by mhamwala** [comment]
@tomleah

**Comment by tomleah** [comment]
Thanks for raising this @mhdawson!

Looks like we just need to enable horizontal scrolling for these blocks @Bazif-Khan

**Comment by mhdawson** [comment]
Also applies to https://appsody.dev/docs/stacks/stack-stucture
