### ISSUE TITLE
Update home page to show only latest/featured stacks

### ISSUE THREAD

**Issue by ddunn2** [appsody/website#445]

**Comment by KyeMaloy97** [comment]
Work has been done on this,  as shown below. The 4 stacks shown are the top stacks we have in terms of Docker Pull numbers.

![Screenshot 2019-12-11 at 10 04 20](https://user-images.githubusercontent.com/24469095/70611748-9ba24400-1bfd-11ea-910d-cbd379e70de0.png)

The Stacks page links will link to a new page being created by @Bazif-Khan in issue #444

**Comment by ddunn2** [comment]
PR merged, great job!
