### ISSUE TITLE
doc: defining a single file mount in APPSODY_MOUNTS is not supported

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#455]
Reference: https://github.com/appsody/appsody/issues/794

Under this issue we'll fix the part of the issue which covers:
1. Document and discourage stack creators from using single file mounts.

The suggestion is to:
i) document this in the environment variables page
ii) also document it in the `Developing stacks` page where is talks about defining env variables for your stack.

**Comment by helenmasters** [comment]
@skoh7645 please can you document part i) in the env variables page?

**Comment by helenmasters** [comment]
@CameronMcWilliam please can you document part ii) in the relevant part of the `Developing stacks` page (it may be linking to the env variable definition will be enough)?

**Comment by CameronMcWilliam** [comment]
I will include this in the stack lifecycle page.

**Comment by helenmasters** [comment]
The phrase "You can specify only directories in volume mounts, not single files." has been added in PR https://github.com/appsody/website/pull/464

**Comment by helenmasters** [comment]
This clarification has been added by Sandy to the environment variables page under PR https://github.com/appsody/website/pull/452. So closing this issue as it's fully documented in both locations.
