### ISSUE TITLE
Determine which existing tutorials should be moved to Appsody.dev

### ISSUE THREAD

**Issue by SueChaplain** [appsody/website#472]
List/confirm the tutorials that should be moved from Medium or elsewhere to the new tutorials page:

- [x] [Make your Express.js app Cloud-Native with Appsody](https://medium.com/appsody/nodejs-express-enablement-f6fc2609bc00)
- [x] [REST on a cloud: easily package a JAX-RS application to deploy to Kubernetes with Appsody](https://medium.com/appsody/rest-on-a-cloud-easily-package-a-jax-rs-application-to-deploy-to-kubernetes-with-appsody-e7ba134a8164)
- [x] [Build a new Cloud Native Express.js app with Appsody](https://medium.com/appsody/nodejs-express-cloud-native-70022e7d5371)
- [x] [Package your Node.js app for Cloud with Appsody](https://medium.com/appsody/nodes-cloud-packaged-fe60e29b699d)
- [x] [Server-Side Swift: Develop in Xcode, Continuously verify in Docker](https://medium.com/appsody/server-side-swift-a77bff1d8f1)
- [x] other........

**Comment by sympatheticmoose** [comment]
https://medium.com/appsody/nodes-functions-839a70289b82
