### ISSUE TITLE
Changing appsody docs for new stack create behaviour

### ISSUE THREAD

**Issue by CameronMcWilliam** [appsody/website#486]
**Is your feature request related to a problem? Please describe.**
In reference to appsody pr [856](https://github.com/appsody/appsody/pull/856)

**Describe the solution you'd like**
Talk about the new possibilities with stack create:

- Able to include custom repos in `appsody stack create --copy` command, (not just stacks that show up in `appsody list`)
- Stack package now creates a tar archive file of the source code of the stack

**Additional context**
To be included in this weeks release on weds/thurs

**Comment by neeraj-laad** [comment]
I think we never explicitly mentioned that the `stack create --copy` command only works for appsody/appsody stacks. Did we? If we did then we need to address that and take that restriction off. 

We should also update any place where we list out what stack package creates/generates.

**Comment by CameronMcWilliam** [comment]
Closed with PR: #501
