### ISSUE TITLE
Add Download Option to Nav Bar

### ISSUE THREAD

**Issue by kylegc** [appsody/website#50]
@erpenbach commented on [Fri Jun 28 2019](https://github.com/appsody/appsody/issues/28)

Add Download link in nav bar to be more consistent with other projects and make it simpler to consume.  Link should go to page that provides context to the versions for installation rather than just a directory of files.

**Comment by sympatheticmoose** [comment]
@kylegc are you thinking https://appsody.dev/docs/getting-started/installation or somewhere else?

**Comment by kylegc** [comment]
Eric Erpenbach originally opened this issue in the appsody repo. I copied it here, but now I know how to transfer issues to preserve the author. I'll close this one and transfer the original here so Eric can comment.
