### ISSUE TITLE
Document correction for "Publishing Stacks"

### ISSUE THREAD

**Issue by mtamboli** [appsody/website#509]
**Describe the bug**
Update the instructions at https://appsody.dev/docs/stacks/publish#publishing-a-stack-using-the-appsody-cli

appsody stack package --image-namespace myproject

still assumes dev.local as registry. 

You need this command so that the images are correctly tagged for a specific registry `appsody stack package --image-namespace my project --image-registry docker.io`

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by helenmasters** [comment]
@mtamboli please can you take a look at the wording and example I've added in the associated pull request, and comment on whether this addresses your issue or not, thanks!
