### ISSUE TITLE
Add search functionality for website/docs

### ISSUE THREAD

**Issue by tomleah** [appsody/website#52]
We need some sort of search on the website so we can traverse all the documentation. See [adding search with Gatsby](https://www.gatsbyjs.org/docs/adding-search/).

- Design, where will the search bar be placed? (desktop and mobile)
- What search library will we use?

**Comment by tomleah** [comment]
@ddunn2 have you looked at implementing search before? I'm looking at using [Algolia](https://www.gatsbyjs.org/docs/adding-search-with-algolia/)

**Comment by ddunn2** [comment]
@tomleah Sorry I didn't see this comment. 
Is [Algolia](https://www.algolia.com/) free to use? Or are you getting a license for it? 

I was looking at using one of the [Open Source](https://www.gatsbyjs.org/docs/adding-search/#use-an-open-source-search-engine) options Gatsby has. 

Once I'm hoping to start looking into this next week :)

**Comment by tomleah** [comment]
I was looking at it based on Gatsby.org using it.
Algolia says:
> Our free offering for small personal projects (non-commercial use)

I haven't looked at `elasticlunr` or `js-search` yet
