### ISSUE TITLE
Review and add icons to "Built on open source" section

### ISSUE THREAD

**Issue by tomleah** [appsody/website#53]
We should expand this to other technologies used by the stacks. I'm not sure if we should just include common technologies or any that are used by a stack.

**Comment by skoh7645** [comment]
Some possible logos we could add:
- [ ] Spring
- [ ] Node
- [ ] Flask
- [ ] Quarkus
- [ ] Microprofile
- [ ] Loopback
- [ ] Swift
- [ ] Knative
- [ ] Docker
- [ ] Golang?

**Comment by ddunn2** [comment]
Closing this issue as we probably won't do this, and hasn't been factored into the design here: #384

Can reopen later if we feel it's required.
