### ISSUE TITLE
Convert JAX-RS tutorial to markdown and update content

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#530]
This issue is to cover converting the following tutorial from medium to appsody.dev [REST on a cloud: easily package a JAX-RS application to deploy to Kubernetes with Appsody](https://medium.com/appsody/rest-on-a-cloud-easily-package-a-jax-rs-application-to-deploy-to-kubernetes-with-appsody-e7ba134a8164)

I've raised an issue for this so that I can collaborate with @awisniew90 and @scottkurz more easily.

**Comment by SueChaplain** [comment]
Closed via https://github.com/appsody/website/pull/531
