### ISSUE TITLE
Create tutorials page and add tutorials to navbar

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#535]
Webdev work required for #195, i.e.:

- Create a tutorials page to be in a tiles format similar to the Blogs page
- Add Tutorials to the navbar (including testing on mobile to make sure we don't break it!)

**Comment by KyeMaloy97** [comment]
Here are some screenshots of the current work done for the Tutorials section of the website. Tried to give it a different feel from the blogs section hence the background, thicker font and translucency, trying to make it a bit more fun and playful.

Opinions welcome!

## Regular, Desktop
<img width="1680" alt="Screenshot 2020-03-09 at 12 43 50" src="https://user-images.githubusercontent.com/24469095/76213938-a328b780-6203-11ea-8ce0-efbd80d30767.png">

## Dark, Desktop
<img width="1680" alt="Screenshot 2020-03-09 at 12 44 27" src="https://user-images.githubusercontent.com/24469095/76213972-b8054b00-6203-11ea-8c58-7644e331c5e8.png">

## Regular, Mobile
<img width="379" alt="Screenshot 2020-03-09 at 12 45 09" src="https://user-images.githubusercontent.com/24469095/76214030-d1a69280-6203-11ea-8c50-76d67904d542.png">

## Tutorial Content
<img width="1680" alt="Screenshot 2020-03-09 at 12 45 37" src="https://user-images.githubusercontent.com/24469095/76214065-e2ef9f00-6203-11ea-8ef3-cd163ad5c854.png">

**Comment by helenmasters** [comment]
These are really different to our other pages. I like the multiple plectrums and translucent nature on the large screens but am not so sure about two large plectrums behind the mobile screen view. 👍  that the text of the actual tutorials doesn't have these images behind.

**Comment by Kamran64** [comment]
I really like these designs (especially the dark mode view)! I think you're right when you say they give the page a much more playful look in contrast to the rest of the website. My only comment is, I wonder if the tiles would benefit by being less transparent to make the content more readable (not sure how that might look though).

**Comment by KyeMaloy97** [comment]
I can change the transparency and blur values to make them a little more opaque. Also I’ve made similar changes to the blogs section of the site (a different but similar background and translucent cards) and I’ll attach a screenshot when I’m next at my laptop

**Comment by CameronMcWilliam** [comment]
I really like this design!  Agree that maybe the text boxes should be slightly more opaque but other than that, great design!

**Comment by sympatheticmoose** [comment]
just needs a toggle for ‘chaos mode’ where the plectrums travel randomly around the screen at different speeds, possibly with bohemian rhapsody playing in the background.

**Comment by neeraj-laad** [comment]
Very different design. It seems a bit overwhelming to me though and my focus is drawn towards the plectrums / hashbrowns instead of the tutorials. 

Can we try to make them less prominent by reducing the size or maybe a bit more transparent to make them a bit subtle?

**Comment by KyeMaloy97** [comment]
I have tweaked the transparency of the tiles to make them less prominent, and ill admit the screenshots are a bit misleading as the design doesnt seem the same when its full screen on my laptop. Also worth noting i have a hover effect where they basically go opaque when you hover over a card. Here are some updated screenshots...

<img width="1680" alt="Screenshot 2020-03-12 at 09 33 18" src="https://user-images.githubusercontent.com/24469095/76507323-84653380-6444-11ea-8685-bd936700077c.png">

<img width="1680" alt="Screenshot 2020-03-12 at 09 33 38" src="https://user-images.githubusercontent.com/24469095/76507349-91822280-6444-11ea-8b35-2b53f630a001.png">

<img width="375" alt="Screenshot 2020-03-12 at 09 34 21" src="https://user-images.githubusercontent.com/24469095/76507402-a959a680-6444-11ea-8d37-d4018306cd2d.png">

<img width="375" alt="Screenshot 2020-03-12 at 09 34 42" src="https://user-images.githubusercontent.com/24469095/76507441-b7a7c280-6444-11ea-9796-33859c0c478c.png">


I have added a similar design for the blogs page too, the image is different though and the titles are a little different

<img width="1680" alt="Screenshot 2020-03-12 at 09 35 29" src="https://user-images.githubusercontent.com/24469095/76507499-d1490a00-6444-11ea-837c-43260b0bf6b4.png">

<img width="1680" alt="Screenshot 2020-03-12 at 09 35 45" src="https://user-images.githubusercontent.com/24469095/76507581-f50c5000-6444-11ea-831b-617d3c32f0ed.png">

**Comment by KyeMaloy97** [comment]
Revised background for tutorials with less doritos and ive made them a bit more transparent, and made the header background darker:  

<img width="1680" alt="Screenshot 2020-03-16 at 11 34 31" src="https://user-images.githubusercontent.com/24469095/76758015-b1854f00-6780-11ea-80e9-e97c14a0c076.png">

**Comment by doveye** [comment]
I think this is definitely an improvement - the plectrums are not as distracting.

**Comment by KyeMaloy97** [comment]
Here is a comment of the tweaks I made to the blogs background image too. Smaller plectrums and made them less bright so the cards stand out.

<img width="1680" alt="Screenshot 2020-03-18 at 15 12 46" src="https://user-images.githubusercontent.com/24469095/76975768-efbe7200-692a-11ea-8c2f-a99689c0e226.png">

One thing i forgot to mention was the changes to the nav bar. @sympatheticmoose we have had to remove the "Home" from the nav bar as there was too many items in it for smaller screens, and on mobile it ran off the edge of the screen. Clicking the apposdy logo takes you home still, are you okay with this change?

**Comment by neeraj-laad** [comment]
I like this new design - definitely an improvement over the previous one... OK from my side to merge this

**Comment by KyeMaloy97** [comment]
What about the nav bar changes I spoke about in my prior comment?

**Comment by KyeMaloy97** [comment]
<img width="1680" alt="Screenshot 2020-03-23 at 10 39 26" src="https://user-images.githubusercontent.com/24469095/77308301-a7200380-6cf2-11ea-90ef-575a597c6dda.png">
<img width="1680" alt="Screenshot 2020-03-23 at 10 39 33" src="https://user-images.githubusercontent.com/24469095/77308308-aa1af400-6cf2-11ea-8c1f-c119c4d659ed.png">

Here are the current up to date screenshots so everyone knows what it looks like at the moment

**Comment by SueChaplain** [comment]
Looks good @KyeMaloy97. The only comment I remember from the last meeting was whether the new design was ok for the blog page, given we have a photo there ATM. Maybe that convo has moved on? @sympatheticmoose ??
