### ISSUE TITLE
Knative docs installs out of date

### ISSUE THREAD

**Issue by josiemundi** [appsody/website#545]
**Describe the bug**
In the docs, for ['Setting up Knative Serving...'](https://appsody.dev/docs/using-appsody/installing-knative-locally/) the Istio version is 1.0.7 and the Knative serving install is 0.7.1.

The docs state that this is '(currently the latest version)'. The latest version of Knative serving is 0.13.0. 

For Istio, the file that is linked to is out of date, it is now up to 1.5.0, however in their [docs](https://knative.dev/docs/install/installing-istio/) they have 1.3.6.

For Knative serving install, there are new install scripts [here.](https://knative.dev/docs/install/any-kubernetes-cluster/) 

**Expected behavior**
Up to date install of Knative

**Actual behaviour**
Out of date install of Knative, which possibly won't work

**Environment Details (please complete the following information):**
NA

**If applicable please specify:**
NA

**Comment by sympatheticmoose** [comment]
In https://appsody.dev/docs/using-appsody/building-and-deploying/#deployment-as-a-knative-service we split out local install and other installs, as I recall this was based on the state of the official docs a the 
 time. The knative project used to provide out a bunch of different install guides, until there was an effort to consolidate https://github.com/knative/docs/issues/2137. I wonder now whether we could just link out to https://knative.dev/docs/install/any-kubernetes-cluster/ or whether we still need any custom guidance.

**Comment by josiemundi** [comment]
Personally, I think linking out to the docs would be fine.

**Comment by neeraj-laad** [comment]
I Agree, we were only documenting this ourselves as a point in time solution while Knative docs were still evolving. We should avoid documenting aspects owned by other projects as we will always be playing catch up.

**Comment by neeraj-laad** [comment]
We should just compare the instructions and make sure there is no additional setup that might be needed for Appsody. Though, I doubt that would be the case.

**Comment by sympatheticmoose** [comment]
Agreed - I think a test with a fresh install following the knative install guide and a quick compare.
