### ISSUE TITLE
Docs: Convert the make your Express app cloud native tutorial

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#554]
Convert the following tutorial to Markdown https://medium.com/appsody/nodejs-express-enablement-f6fc2609bc00. 

Test all the steps are still current and work, including upping any referenced versions to the current stack levels, if relevant.

**Comment by helenmasters** [comment]
@sam-github I've taken a look at this next tutorial and the steps within it. Following on from the previous tutorial which you reviewed this one also refers (in Step 3) to exporting the `Express.js` object from the file as `module.export.app`, unsurprisingly this doesn't work:

"Export the Express.js app object from the file as module.exports.app:
The last line of the app.js file should become:
```
module.exports.app = app;
```
This exposes the app object so that the nodejs-express Appsody stack can apply it onto its own pre-configured Express.js server that includes the cloud-native capabilities."

Please can you suggest:

1. an adaptation to the wording at the end of Step 2 which is currently:

"Here `main` references `app.js` as that is the file that contains the `Express.js` `app` object. The next step is to export the `app` object from that file."

and

2. some replacement code and wording for Step 3.

Thanks!

**Comment by sam-github** [comment]
`module.exports.app = app;` would likely become `module.exports = () => app;`

**Comment by helenmasters** [comment]
@ddunn2 I've made some text updates to this tutorial from medium in line with Sam's comments (and to line it up with the other tutorial I converted). I've emailed the file to you for formatting, adding front matter and running through to check it all works.

When you're done please can you raise a PR and make myself and Sam Roberts the reviewers. Thanks!

**Comment by helenmasters** [comment]
Closing as this is now complete.
