### ISSUE TITLE
Tutorial: Make your Node.js Express app cloud native and deploy to Knative 

### ISSUE THREAD

**Issue by sympatheticmoose** [appsody/website#58]
'Bring your own application' scenario. I think both a video demo and blog/tutorial post would make sense for this, and I can do both at the same time

**Comment by neeraj-laad** [comment]
https://medium.com/appsody/nodejs-express-enablement-f6fc2609bc00

**Comment by neeraj-laad** [comment]
@sympatheticmoose We do have a blog on this topic now, are you planning to create a video to cover this as well?

**Comment by neeraj-laad** [comment]
Closing this one as we do have a tutorial for this.
