### ISSUE TITLE
Should autogenerated tags be visible in docs?

### ISSUE THREAD

**Issue by mhdawson** [appsody/website#64]
These show up in https://appsody.dev/docs/using-appsody/cli-commands
```
Auto generated by spf13/cobra on 24-Jun-2019
````

as well as in the markdown files in the doc repo.  Are they intended to be visible to end users?

**Comment by kewegner** [comment]
The new cli-docs have removed theses statements as of 0.2.4.

**Comment by mhamwala** [comment]
related: https://github.com/appsody/website/pull/75/files
