### ISSUE TITLE
Rename documentation titles to be clearer

### ISSUE THREAD

**Issue by tomleah** [appsody/website#76]
**Is your feature request related to a problem? Please describe.**
I think some of the documentation titles should be renamed for clarity.

**Describe the solution you'd like**
`Creating and Modifying Stacks` -> `Creating and Modifying` 
- This only needs to be changed in the website sidebar as currently, it is too long. The fact it's under the stacks section is good enough?

`Creating Projects` -> `Initializing Projects` 
- This needs discussion, maybe it should be changed to `Initializing a Project` or similar.
- This should be changed in both website sidebar and the doc.

Let's discuss this proposal before implementing.

**Comment by neeraj-laad** [comment]
I personally do not like the title to be just `creating and modifying`, especially when other titles have the work `stack` in them.. 

But I want to make sure that these items do not scroll over to the next line, at least on a standard desktop monitor/resolution. 

Any chance we can have 2 menus.. one for `Creating Stacks` and one for `Modifying Stacks`?
