### ISSUE TITLE
Improve guidance for stack creators

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/website#79]

**Comment by tomleah** [comment]
In what area did we want to improve here? 
IIRC was this to do with fleshing out `stacks/create-or-modify.md`? 

cc: @mhamwala

**Comment by tomleah** [comment]
What we want to cover here:

- Creating a stack (from scratch)
  - What will be created? (image/templates)
  - What is included in a Dockerfile-stack

- Modifying an existing stack
  - Raising a pull request to upstream
  - Maintaining your own version of an existing stack

- How do you test a stack?
