### ISSUE TITLE
Add stack status tag to stack tiles

### ISSUE THREAD

**Issue by tomleah** [appsody/website#83]
Lets add a tag on the tile that says `incubator` or `experimental`. I don't think we need to show a `stable` status but this is up for discussion.

We should discuss:
- Where the tag should be put on the tile
- Should the tag be shown of both flipped states?
- Should the tag display if the stack is `stable`?

**Comment by mhamwala** [comment]
My preference would be to have the status bar just below the select button for now, possibly not on both sides, let's see how this looks with the stable label as well:

Add a screenshot below if you can :)

**Comment by Kamran64** [comment]
Something like this?

<img width="1050" alt="Screenshot 2019-07-22 at 08 44 32" src="https://user-images.githubusercontent.com/45264227/61615101-1d98cd00-ac5d-11e9-9d61-19dd40f78c34.png">

**Comment by Kamran64** [comment]
Updated

<img width="1127" alt="Screenshot 2019-07-22 at 11 10 50" src="https://user-images.githubusercontent.com/45264227/61624947-7f633200-ac71-11e9-9aee-9ae6ccade6fb.png">

**Comment by neeraj-laad** [comment]
The second screenshot looks better, however, I'd like to explore the possibility of using graphic / icon to indicate this.

**Comment by mdenby** [comment]
So I'm imagining that more stacks will be add in each category--"Stable", "Incubator", and "Experimental". With that in mind, what if we had a content switcher?

<img width="1260" alt="Screen Shot 2019-08-20 at 5 13 08 PM" src="https://user-images.githubusercontent.com/26823018/63384970-05a48e00-c36e-11e9-9557-309f94fb3b3a.png">

**Comment by sympatheticmoose** [comment]
I don't think this is the right focus for how we improve the disclosure of available Stacks.

I'm worried just adds confusion on the first step, by introducing the concepts of stable/incubator/experimental without explaining what any of that means. Neither does it solve any issues of scalability as we look to grow the number of stacks available to folks. 

This isnt a comment on any of the proposed designs/implementations, but a comment that this needs more discussion.

**Comment by ddunn2** [comment]
Closing this issue as work is being tracked here: #231
