### ISSUE TITLE
docs: fix links that have a relative path starting with /docs

### ISSUE THREAD

**Issue by mhamwala** [appsody/website#88]
**Describe the bug**
The links that have a relative path starting with /docs are broken because they are not from the project root. when we added the docs repo to the website the new root starts with /content/docs

**To Reproduce**
Click a link that has a root starting with /docs

**Expected behavior**
Takes you to the referenced doc

**Actual behaviour**
Broken link page

**Environment Details (please complete the following information):**
n/a

**If applicable please specify:**
 - CLI version: n/a
 - Stack you are using: n/a

**Screenshots**

**Additional context**

**Comment by tomleah** [comment]
**Note:** this is when you are navigating the docs on GitHub and not on the website.

Proposed fix: move `/content/docs` to `/docs` until it is clear if we need to be able to traverse docs in GitHub.

Alternatively: replace all occurrences of `/docs` with `/content/docs`. Then trim the `/content` when generating the website.

Discuss the requirement of being able to traverse docs within GitHub.

**Comment by tomleah** [comment]
See:
- https://github.com/reactjs/reactjs.org
- https://github.com/gatsbyjs/gatsby

where links seem to be broken on GitHub

**Comment by mhamwala** [comment]
this was fixed, we moved `/content/docs` to `/docs`
