### ISSUE TITLE
Improve ambiguous description in Appsody doc

### ISSUE THREAD

**Issue by davco01a** [appsody/website#90]
## Summary
at:  https://appsody.dev/docs

This statement is ambiguous and unclear:

"Our aims were to simplify the experience for developers - now asked to have full-stack expertise and responsibilities, and allow them to focus on their application code; and to enable architects to curate an opinionated set of technologies - configurable, reusable and already infused with cloud native capabilities."

perhaps:

"Our aims were to simplify the experience for developers, relieving them of full-stack expertise and responsibilities, and allowing them to focus on their application code development activities; enabling architects to curate an opinionated set of technologies - configurable, reusable and already infused with cloud native capabilities, making them seamlessly available to application developers"

Something like that....

Unless I'm missing or misunderstanding something

**Comment by kewegner** [comment]
@neeraj-laad I think this belongs in the website project, as it is part of the Website page info.

**Comment by neeraj-laad** [comment]
This looks reasonable to me..
@sympatheticmoose would like your thoughts on the suggested words.

**Comment by davco01a** [comment]
I provided a suggestion in the first comment after `perhaps:`
