### ISSUE TITLE
add swift to initialising project docs

### ISSUE THREAD

**Issue by mhamwala** [appsody/website#94]
**Describe the bug**
We recently added the swift stack, we should also include swift in the section where it states the available stacks in the `appsody list` command.

**To Reproduce**
https://github.com/appsody/website/blob/a0811b8c873512575b378a08f6dd6c50f2aa4030/content/docs/using-appsody/initializing-project.md

**Expected behavior**
showcase the swift stack as part of the `appsody list` command.

**Actual behaviour**
showcases 4 stacks, we currently have 5

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
Perhaps, we should just adjust the wording on this page to make it clearer that the list shown is just an example and might not be the same as what the user sees.
